# Overall statistics for all three villages
overall_rt <- c()
overall_r0 <- c()
overall_eta <- c()
overall_eta_best <- c()
load(file=paste0("~/vaxMada-data/objects/data_obj/sims_sensR.RData"))
overall_rt <- c(overall_rt, sims$rt)
overall_r0 <- c(overall_r0, sims$r0)
eta_dist_zero <- ifelse(sims$eta < 0, 0, sims$eta)
overall_eta <- c(overall_eta, eta_dist_zero)
overall_eta_best <- c(overall_eta_best, ifelse(sims$eta_best < 0, 0, sims$eta_best))
load(file=paste0("~/vaxMada-data/objects/data_obj/sims_vill2_sensR.RData"))
overall_rt <- c(overall_rt, sims$rt)
overall_r0 <- c(overall_r0, sims$r0)
eta_dist_zero <- ifelse(sims$eta < 0, 0, sims$eta)
overall_eta <- c(overall_eta, eta_dist_zero)
overall_eta_best <- c(overall_eta_best, ifelse(sims$eta_best < 0, 0, sims$eta_best))
load(file=paste0("~/vaxMada-data/objects/data_obj/sims_vill3_sensR.RData"))
overall_rt <- c(overall_rt, sims$rt)
overall_r0 <- c(overall_r0, sims$r0)
eta_dist_zero <- ifelse(sims$eta < 0, 0, sims$eta)
overall_eta <- c(overall_eta, eta_dist_zero)
overall_eta_best <- c(overall_eta_best, ifelse(sims$eta_best < 0, 0, sims$eta_best))
mean(overall_rt, na.rm=T)
sd(overall_rt, na.rm=T)
mean(overall_r0, na.rm=T)
sd(overall_r0, na.rm=T)
mean(overall_eta, na.rm=T)
sd(overall_eta, na.rm=T)
mean(overall_eta_best, na.rm=T)
sd(overall_eta_best, na.rm=T)
